build_from: 
  aarch64: "python:alpine"
  amd64: "python:alpine"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: ptbsare add-on"
  org.opencontainers.image.description: "Wyoming integration for sherpa-onnx TTS and STT."
  org.opencontainers.image.source: "https://github.com/ptbsare/home-assistant-addons"
  org.opencontainers.image.licenses: "MIT"
