build_from: 
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
  armv7: "ghcr.io/home-assistant/armv7-base:latest"
  armhf: "ghcr.io/home-assistant/armhf-base:latest"
  i386: "ghcr.io/home-assistant/i386-base:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: ptbsare add-on"
  org.opencontainers.image.description: "Wyoming integration for sherpa-onnx TTS and STT."
  org.opencontainers.image.source: "https://github.com/ptbsare/home-assistant-addons"
  org.opencontainers.image.licenses: "MIT"
