name: Sherpa Onnx TTS/STT
version: "0.1.9"
slug: sherpa_onnx_tts_stt
description: Wyoming integration for sherpa-onnx TTS and STT. (Supports Chinese For Now. It just works. For Multi-language/Custimaze Port/Custimaze Model Support, PR is Welcomed.)
url: https://github.com/ptbsare/home-assistant-addons/tree/main/sherpa-onnx-tts-stt
arch:
  - amd64
  - aarch64
startup: application
discovery:
  - wyoming
backup_exclude: []
boot: auto
init: false
options:
    language: zh-CN
    speed: 1.0
schema:
    language: str?
    speed: float?
ports:
  10400/tcp: 10400
homeassistant: 2023.8.0.dev20230728
image: "ghcr.io/ptbsare/home-assistant-addons/{arch}-addon-sherpa-onnx-tts-stt"
